Testing with rspec
lucaasdfg/Advanced-Building-Blocks---Enumerables pull request #2
Opened 2019-11-13 20:00 UTC by lucaasdfg

2019-11-14 05:08 UTC, maelfosso requested changes
# Changes required

Hello @lucaasdfg 

Awesome, Amazing. Nothing to add except only one thing **Constant declaration**
For constant declarations, please use `let`. Read the comment to know how.

Kindly make the change and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-14 05:08 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  falsy_array = [1, 22, false, 0, 'oop']
Not good !!!
Do
```ruby
let(array) {[1,2,3,4,5]}
...
```

2019-11-15 03:06 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**You have done a great job on this on this project, however, we still have one thing to update! ⬇️** 

- Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-11-15 17:16 UTC, ebukaume approved these changes
## Approved! :champagne: 

Hi @lucaasdfg and @alexawesomecode :wave: 

The README now looks more descriptive :+1: 

**You can go ahead and merge this branch**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-15 19:37 UTC, merged